### ISSUE TITLE
Add Brotli support for compression

### ISSUE THREAD

**Issue by thomasvvugt** [gofiber/compression#1]
Hello team,
I'd like to add an idea to support Brotli for compression. Research has proven that Brotli is faster than Gzip, especially when compressing static files (see the links below).
Therefore it would be nice to implement Brotli in both Fiber's main application as well as the compression and/or embed middleware.
I haven't really got the time to determine whether these articles have been biased. Please let me know what you think!

https://wp-rocket.me/blog/brotli-vs-gzip-compression/
https://medium.com/oyotech/how-brotli-compression-gave-us-37-latency-improvement-14d41e50fee4

**Comment by thomasvvugt** [comment]
Additional comment: I don't think the current embed middleware even has compression/caching. Correct me if I am wrong 😊

**Comment by renanbastos93** [comment]
Hey dude, time ago I studied Brotli these articles aren't biased. I liked the idea to we implement on Fiber.

**Comment by thomasvvugt** [comment]
The PR https://github.com/caddyserver/caddy/pull/2590 got merged in fasthttp. I am working on a possible integration with Fiber.

**Comment by thomasvvugt** [comment]
I am awaiting a new release tag for `fasthttp` which will include Brotli compression, we'd only have to re-write the compression level for support.
