### ISSUE TITLE
Static files from ServeFile

### ISSUE THREAD

**Issue by suntong** [gofiber/compression#2]
I'm wondering if the Static files from `http.ServeFile` method is also supported. Especially,

It would also be 'nice to have' if the http.ServeFile method would check for the presence of xxx.gz and serve it if present and the accept header includes gzip. This is a trick that nginx does and it greatly accelerates the serving of static css, js etc files because they can be compressed just once during the build process. There's the added benefit too that they are smaller files to read, as well as needing fewer bytes on the wire

thanks

**Comment by Fenny** [comment]
Hi @suntong, we have a `ctx.SendFile()` in the Fiber web framework that will automatically compress the file once, and by default checks if the `.gz` file already exists and re-use it. The same goes for `app.Static()`

https://docs.gofiber.io/application#static
https://docs.gofiber.io/context#sendfile

The compression middleware is for Dynamic responses ( generated XML / JSON / Templates )

**Comment by suntong** [comment]
> The same goes for app.Static()
https://docs.gofiber.io/application#static

Thanks @Fenny, just to make it 100% clear, with

```
// Serve files from "./public" directory:
app.Static("/", "./public")
```

Files under `./public` like `mycss.css.gz`, `myjs.js.gz` or `myfile.html.gz` will be automatically served as-is (compressed), with a header includes `gzip`, correct?

**Comment by Fenny** [comment]
Correct!

**Comment by suntong** [comment]
Thanks Fenny

**Comment by suntong** [comment]
> just to make it 100% clear, with
> 
> ```
> // Serve files from "./public" directory:
> app.Static("/", "./public")
> ```
> 
> Files under `./public` like `mycss.css.gz`, `myjs.js.gz` or `myfile.html.gz` will be automatically served as-is (compressed), with a header includes `gzip`, correct?

Hi Fenny, please reopen as my test result doe not backup above -- please take a look at

https://github.com/suntong/fiber_demo/tree/master/web/sample2

in which I have `index.html.gz`, `index.js.gz` and `styles.css.gz`. 

Again, the anticipated behavior is that `Static()` would check for the presence of xxx.gz and serve the `xxx` counterpart version and the accept header includes gzip.

Maybe I missed some steps, like turning on compression? My code is at
https://github.com/suntong/fiber_demo/blob/master/app/static1.go

I.e., I serve `sample2` non-differently than `sample0`.

**Comment by suntong** [comment]
In case you've tried before my this comment, I just pushed an updated (corrected) version of `sample2`.
